### ISSUE TITLE
JSX / UI Framework Compatibility

### ISSUE THREAD

**Issue by FicoPrieto** [edDimensi/html2pug#6]
There are currently a few issues that prevent this tool from accurately converting templates from popular UI frameworks like Material-UI, Blueprint, Vuetify, etc.

## [ 1 ]

Word case is not preserved. This results in invalid element & variable names since these names are eventually consumed by JavaScript, where their usage is case-sensitive. 

## [ 2 ]

Self-closing tags break the hierarchy. Tags that should be siblings of self-closing tags are rendered as children instead.

## [ 3 ]

Tag attributes that are delimited for interpolation in JavaScript are converted to multiple string attributes, apparently being split by spaces. Altering this might conflict with the HTML spec, so it would be best implemented as an option like `Preserve Javascript Interpolation` that defaults to `false`.

An example of the behavior when set to `true` would be that

```html
<div foo={bar ? bar : baz}/>
```

renders as

```pug
div(foo="{bar ? bar : baz}")
```

instead of 

```pug
div(foo="{bar", ?="", bar="", :="", baz}="")
```

&nbsp;  
## Example

```html
<Navbar>
  <NavbarGroup align={alignRight ? Alignment.RIGHT : Alignment.LEFT}>
    <NavbarHeading>Blueprint</NavbarHeading>
    <NavbarDivider/>
    <Button className={Classes.MINIMAL} icon="home" text="Home"/>
    <NavbarDivider/>
    <Button className={Classes.MINIMAL} icon="document" text="Files"/>
  </NavbarGroup>
</Navbar>
```

is rendered as 

```pug
navbar
  navbargroup(align="{alignRight", ?="", alignment.right="", :="", alignment.left}="")
    navbarheading Blueprint
    navbardivider
      button(classname="{Classes.MINIMAL}", icon="home", text="Home")
        navbardivider
          button(classname="{Classes.MINIMAL}", icon="document", text="Files")
```

but should be rendered as

```pug
Navbar
  NavbarGroup(align="{alignRight ? Alignment.RIGHT : Alignment.LEFT}")
    NavbarHeading Blueprint
    NavbarDivider
    Button(className="{Classes.MINIMAL}", icon="home", text="Home")
    NavbarDivider
    Button(className="{Classes.MINIMAL}", icon="document", text="Files")
```

**Comment by dimensi** [comment]
I'll see what I can do. 
Also PR is welcome.

**Comment by dimensi** [comment]
@trasherdk. After research, I came to the conclusion that this feature would require too much effort. I'd have to rewrite the project from scratch. I don't have that much free time.

I will explain the reason why none of the items can be done without rewriting.

Initially I used the [html2jade](https://github.com/donpark/html2jade) library, after I was asked to add "[inline css](https://github.com/dimensi/html2pug/issues/2)". Since the library is no longer supported by anyone, I had to copy it to myself and fix the right places and the code is not really mine and adapt it to the new feature is too difficult, it is easier to rewrite from scratch.

And now for the features, all three points that you specified are impossible in the html specification. All existing html parsers follow the html specification.
For example: [parse5](https://github.com/inikulin/parse5), [himalaya](https://github.com/andrejewski/himalaya), [hyntax](https://github.com/mykolaharmash/hyntax).
According to html specification all html tags should be case insensitive and therefore parsers lead all tags to lower case.
There is also a strict set of tags that can be self-closing and all other self-closing tags are considered simply broken.
And finally `{ }` this is not supported in any way by the html specification and everything inside them can be considered as new attributes by the parser.

To solve your problem, I will need to rewrite the code so that I can switch between parsers. In this situation between html and jsx. And it will take too much time which I don't have for this project.

If you want, you may fork my project or open pr with a solution.


You can close the issue yourself or I'll close it in a week.

**Comment by trasherdk** [comment]
@dimensi budy. I'm kinda confused, why you have me referenced in this issue?
I'm a user of your module, and has no objections to your stewardship.
So far, it makes sense to me, and I do believe your knowledge in this matter supersedes mine substantially.
I believe, and trust, you will continue the path of the clean tool you have provided so far.
I feel, if those frameworks want to utilize your work, they should do the work. Like sugestions/PR's how to accomplish what they are looking for.

The dude that opened the issue was @FicoPrieto maybe you want to direct your comments to him ?

**Comment by dimensi** [comment]
Yeah, you're right. I accidentally pointed you out :) Sorry.
